version = 0.1

[default.validate.parameters]
lint = false

[prod.deploy.parameters]
stack_name = "brainink-users-micro"
resolve_s3 = true
s3_prefix = "brainink-users-micro"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
parameter_overrides = "Algorithm=\"HS256\" AlgorithmData=\"HS256\" DbUser=\"__SET_DB_USER__\" DbHost=\"__SET_DB_HOST__\" DbPort=\"5432\" DbName=\"__SET_DB_NAME__\" BraininkUsername=\"__SET_BRAININK_USERNAME__\" BraininkSenderEmail=\"noreply@example.com\" AccessTokenExpireMinutes=\"1440\" Environment=\"production\" Debug=\"false\" GoogleClientId=\"__SET_GOOGLE_CLIENT_ID__\" KanaBaseUrl=\"http://localhost:10000\" ViteGoogleClientId=\"__SET_VITE_GOOGLE_CLIENT_ID__\" ViteApiBaseUrl=\"http://localhost:8000\" ViteOcrServiceUrl=\"http://localhost:8001\" ViteKanaApiBaseUrl=\"https://kana-backend-app.onrender.com/api/kana\" KanaApiUrl=\"https://kana-backend-app.onrender.com\" ViteAgentApiBaseUrl=\"https://brainink.onrender.com\" AgentApiBaseUrl=\"https://kana-backend-app.onrender.com\" AgentSystemEnabled=\"true\" BraininkAgentPort=\"443\" BraininkAgentUrl=\"https://brainink.onrender.com\""
